### ISSUE TITLE
Make it easier for people to add/edit abbreviations

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/acronyms#3]
Create an issue template for adding/editing an entry in the list, and put a link to the issue template  near the top of the README file, so that people can see how to update the list if they're not familiar with git/github.

This won't help people who don't have a github account, but it's a start.

**Comment by MatMoore** [comment]
You could link directly to this page? https://github.com/ministryofjustice/acronyms/edit/master/README.md
