### ISSUE TITLE
Search includes non-matching rows

### ISSUE THREAD

**Issue by rossjones** [ministryofjustice/acronyms#83]
When I search for an acryonym, as well as the matching result, any acronyms that are links are also included.  
For example, if I search for PTTP it does show the result below the fold, but it also includes every linked acryonym in the first field.

![Ministry_of_Justice_Acronyms](https://user-images.githubusercontent.com/118063/154035945-bd9719ac-1d39-47e0-ab03-dc270fbdc0f0.png)

The issue appears to be at https://github.com/ministryofjustice/acronyms/blob/main/template/acronyms.jinja2#L82-L86 where a cell with a link is created as `td` instead of `th` and the `searchFunction` is only checking for `th` cells.

**Comment by AntonyBishop** [comment]
Thanks @rossjones. Will bring in for triage and prioritisation.

**Comment by ben-al** [comment]
Have reviewed the PR - happy to merge
